---
# tasks file for azure-cli
- name: paquet prerequis
  apt:
    name:
    - ca-certificates
    - curl 
    - apt-transport-https
    - lsb-release 
    - gnupg 

- name: add key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Create the APT repository (Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://download.sublimetext.com/ apt/stable/"
    filename: sublimetext
    state: present

- name: Install the application package
  apt:
    name: sublime-text
    update_cache: yes
