---
# tasks file for wireshark
- name: wireshark is present
  shell: dpkg-query -W 'wireshark'
  ignore_errors: True
  register: wireshark_status

- name: add key 
  apt_key:
    id: D875551314ECA0F0
    keyserver: keyserver.ubuntu.com
    state: present
- name: add repo 
  apt_repository:
    repo:  ppa:wireshark-dev/stable
    state: present
    filename: wireshark
  when: ansible_distribution == "Ubuntu"

- name: add repo
  apt_repository:
    repo: "{{ wireshark_repo_ubuntu }}"
    state: present
    filename: wireshark
  when: ansible_distribution == "Linux Mint"

- name: let non root to capture traffic
  # Before installing any package, this only sets the preference for the question
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'
  when: wireshark_status is failed 

- name: install wireshark
  apt: 
    name: wireshark 
    state: present
    update_cache: yes
  when: wireshark_status is failed 

- name: add current user to wireshark group
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: wireshark
  when: wireshark_status is failed
