---
# tasks file for osbproject
- name: add key
  apt_key:
    id: EFC71127F425E228 
    keyserver: keyserver.ubuntu.com
    state: present
  
- name: add ppa 
  apt_repository:
    repo: ppa:obsproject/obs-studio
    filename: obsproject
  when: ansible_distribution == "Ubuntu"

- name: add repo
  apt_repository:
    repo: "{{ obs_ubuntu_repo }}"
    state: present
    filename: obsproject-obs-studio-bionic 
  when: ansible_distribution == "Linux Mint"

- name: Install obs-studio
  apt:
    name: obs-studio
    update_cache: yes
